Global-client-fingerprint: chrome
port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7894
allow-lan: true
tcp-concurrent: true
enable-process: true
find-process-mode: strict
ipv6: false
log-level: debug
geo-auto-update: true
geo-update-interval: 168
secret: ''
bind-address: '*'
unified-delay: false
disable-keep-alive: false
keep-alive-idle: 30
keep-alive-interval: 30
profile:
  store-selected: true
  store-fake-ip: true
dns:
  enable: true
  ipv6: false
  respect-rules: false
  prefer-h3: false
  cache-algorithm: arc
  use-system-hosts: true
  use-host: true
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip
  fake-ip-filter-mode: blacklist
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
  - '*.lan'
  - '*.localdomain'
  - '*.invalid'
  - '*.localhost'
  - '*.test'
  - '*.local'
  - '*.home.arpa'
  - time.*.com
  - ntp.*.com
  - '*.ir'
  default-nameserver:
  - 8.8.8.8
  - 8.8.4.4
  - 1.0.0.1
  - 1.1.1.1
  - 9.9.9.9
  - 9.9.9.11
  - 9.9.9.10
  - 94.140.14.15
  - 94.140.15.15
  - 223.5.5.5
  - 77.88.8.8
  - 208.67.222.222
  - 208.67.220.220
  - 209.244.0.3
  - 209.224.0.4
  - 74.82.42.42
  nameserver:
  - https://dns.nextdns.io/15441b
  - tls://15441b.dns.nextdns.io
  direct-nameserver:
  - 78.157.42.100
  - 78.157.42.101
  proxy-server-nameserver:
  - 1.1.1.1
  - 8.8.8.8
  - 8.8.4.4
  - 9.9.9.9
  - 223.5.5.5
  - 77.88.8.8
  - 208.67.222.222
  - 208.67.220.220
  - 209.244.0.3
  - 209.224.0.4
  - 74.82.42.42
sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: false
  sniff:
    HTTP:
      ports:
      - 80
      - 8080
      - 8880
      - 2052
      - 2082
      - 2086
      - 2095
    TLS:
      ports:
      - 443
      - 8443
      - 2053
      - 2083
      - 2087
      - 2096
tun:
  enable: true
  stack: mixed
  auto-route: true
  auto-detect-interface: true
  auto-redir: true
  dns-hijack:
  - any:53
  - tcp://any:53
proxies:
- name: 🇯🇵JP-13.231.108.161-0382
  type: ssr
  server: jp-am48-6.eqnode.net
  port: 8081
  cipher: aes-256-cfb
  password: eAokbaDN6
  obfs: tls1.2_ticket_auth
  protocol: origin
  obfs-param: ''
  protocol-param: ''
  udp: true
- name: 🇨🇦CA-45.154.204.13-5132
  type: ssr
  server: ssca.irundns.net
  port: 443
  cipher: aes-128-cfb
  password: $$Turb0VPN$$
  obfs: http_post
  protocol: auth_aes128_md5
  obfs-param: ''
  protocol-param: ''
  udp: true
proxy-groups:
- name: نوع انتخاب پروکسی 🔀
  icon: https://www.svgrepo.com/show/412721/choose.svg
  type: select
  proxies:
  - خودکار (بهترین پینگ) 🤖
  - دستی 🤏🏻
  - پشتیبان (در صورت قطعی) 🧯
  - بدون فیلترشکن 🛡️
- name: دستی 🤏🏻
  type: select
  icon: https://www.svgrepo.com/show/372331/cursor-hand-click.svg
  proxies:
  - 🇭🇰香港 大B哥赞助
  - 🇯🇵日本 01
  - 🇯🇵日本 02
  - 🇯🇵日本 03
  - 🇸🇬新加坡 01
  - 🇸🇬新加坡 02
  - 🇸🇬新加坡 03
  - 🇺🇸美国 01
  - 🇺🇸美国 02
  - 🇺🇸美国 03
  - 'Channel id: @ShadowProxy66🇭🇰'
  - 'Channel id: @ShadowProxy66🇺🇸'
  - 剩余流量：0
  - 套餐到期：2036-07-12
  - 新加坡
  - 距离下次重置剩余：7 天
  - 美国02
  - 美国03
  - 美国01
  - 🇯🇵JP-13.231.108.161-0382
  - 🇨🇦CA-45.154.204.13-5132
  - Anon10
  - $$$+jadid+💪💪💪@freeiranianv2rey
  - mci jadid 💪💪💪@freeiranianv2rey
  - Peyman_wire-g
  - Peyman_wire-g
  - Anon7
  - Anon2
  - کانال+freeiranianv2rey
  - jadid+💪💪💪@freeiranianv2rey
  - '@freeiranianv2rey+💯💯💯تا+ابد+رایگان'
  - پرقدرت@freeiranianv2rey
  - wg-2606:4700:d0::d91:179:c651:ed70
  - Peyman_wire-g
  - Peyman_wire-g
  - Anon6
  - Anon8
  - Peyman_wire-g
  - Peyman_wire-g
  - Anon5
  - Anon4
  - Peyman_wire-g
  - Anon3
  - Peyman_wire-g
  - Peyman_wire-g
  - Anon9
  - Anon1
  - Peyman_wire-g
- name: خودکار (بهترین پینگ) 🤖
  type: url-test
  icon: https://www.svgrepo.com/show/7876/speedometer.svg
  url: https://api.v2fly.org/checkConnection.svgz
  interval: 360000
  timeout: 120000
  tolerance: 10
  lazy: true
  proxies:
  - 🇭🇰香港 大B哥赞助
  - 🇯🇵日本 01
  - 🇯🇵日本 02
  - 🇯🇵日本 03
  - 🇸🇬新加坡 01
  - 🇸🇬新加坡 02
  - 🇸🇬新加坡 03
  - 🇺🇸美国 01
  - 🇺🇸美国 02
  - 🇺🇸美国 03
  - 'Channel id: @ShadowProxy66🇭🇰'
  - 'Channel id: @ShadowProxy66🇺🇸'
  - 剩余流量：0
  - 套餐到期：2036-07-12
  - 新加坡
  - 距离下次重置剩余：7 天
  - 美国02
  - 美国03
  - 美国01
  - 🇯🇵JP-13.231.108.161-0382
  - 🇨🇦CA-45.154.204.13-5132
  - Anon10
  - $$$+jadid+💪💪💪@freeiranianv2rey
  - mci jadid 💪💪💪@freeiranianv2rey
  - Peyman_wire-g
  - Peyman_wire-g
  - Anon7
  - Anon2
  - کانال+freeiranianv2rey
  - jadid+💪💪💪@freeiranianv2rey
  - '@freeiranianv2rey+💯💯💯تا+ابد+رایگان'
  - پرقدرت@freeiranianv2rey
  - wg-2606:4700:d0::d91:179:c651:ed70
  - Peyman_wire-g
  - Peyman_wire-g
  - Anon6
  - Anon8
  - Peyman_wire-g
  - Peyman_wire-g
  - Anon5
  - Anon4
  - Peyman_wire-g
  - Anon3
  - Peyman_wire-g
  - Peyman_wire-g
  - Anon9
  - Anon1
  - Peyman_wire-g
- name: پشتیبان (در صورت قطعی) 🧯
  type: fallback
  icon: https://www.svgrepo.com/show/415208/backup-cloud-document.svg
  url: https://www.gstatic.com/generate_204
  interval: 360000
  timeout: 120000
  tolerance: 6
  lazy: true
  proxies:
  - 🇭🇰香港 大B哥赞助
  - 🇯🇵日本 01
  - 🇯🇵日本 02
  - 🇯🇵日本 03
  - 🇸🇬新加坡 01
  - 🇸🇬新加坡 02
  - 🇸🇬新加坡 03
  - 🇺🇸美国 01
  - 🇺🇸美国 02
  - 🇺🇸美国 03
  - 'Channel id: @ShadowProxy66🇭🇰'
  - 'Channel id: @ShadowProxy66🇺🇸'
  - 剩余流量：0
  - 套餐到期：2036-07-12
  - 新加坡
  - 距离下次重置剩余：7 天
  - 美国02
  - 美国03
  - 美国01
  - 🇯🇵JP-13.231.108.161-0382
  - 🇨🇦CA-45.154.204.13-5132
  - Anon10
  - $$$+jadid+💪💪💪@freeiranianv2rey
  - mci jadid 💪💪💪@freeiranianv2rey
  - Peyman_wire-g
  - Peyman_wire-g
  - Anon7
  - Anon2
  - کانال+freeiranianv2rey
  - jadid+💪💪💪@freeiranianv2rey
  - '@freeiranianv2rey+💯💯💯تا+ابد+رایگان'
  - پرقدرت@freeiranianv2rey
  - wg-2606:4700:d0::d91:179:c651:ed70
  - Peyman_wire-g
  - Peyman_wire-g
  - Anon6
  - Anon8
  - Peyman_wire-g
  - Peyman_wire-g
  - Anon5
  - Anon4
  - Peyman_wire-g
  - Anon3
  - Peyman_wire-g
  - Peyman_wire-g
  - Anon9
  - Anon1
  - Peyman_wire-g
- name: تلگرام 💬
  type: select
  icon: https://www.svgrepo.com/show/354443/telegram.svg
  proxies:
  - نوع انتخاب پروکسی 🔀
  - بدون فیلترشکن 🛡️
  - خودکار (بهترین پینگ) 🤖
  - دستی 🤏🏻
  - پشتیبان (در صورت قطعی) 🧯
  - اجازه ندادن 🚫
- name: سایتای ایرانی 🇮🇷
  type: select
  icon: https://upload.wikimedia.org/wikipedia/commons/3/36/Flag_of_Iran_%28civil%29.svg
  proxies:
  - بدون فیلترشکن 🛡️
  - اجازه ندادن 🚫
  - نوع انتخاب پروکسی 🔀
  - خودکار (بهترین پینگ) 🤖
  - دستی 🤏🏻
  - پشتیبان (در صورت قطعی) 🧯
- name: بدون فیلترشکن 🛡️
  type: select
  icon: https://www.svgrepo.com/show/6318/connection.svg
  proxies:
  - DIRECT
  hidden: true
- name: اجازه ندادن 🚫
  type: select
  icon: https://www.svgrepo.com/show/444307/gui-ban.svg
  proxies:
  - REJECT
  hidden: true
rule-providers:
  apps:
    type: http
    format: yaml
    behavior: classical
    url: https://github.com/chocolate4u/Iran-clash-rules/releases/latest/download/apps.yaml
    path: ./ruleset/apps.yaml
    interval: 86400
rules:
- PROCESS-NAME,Telegram.exe,تلگرام 💬
- PROCESS-NAME,org.telegram.messenger,تلگرام 💬
- PROCESS-NAME,org.telegram.messenger.web,تلگرام 💬
- DOMAIN-SUFFIX,ir,سایتای ایرانی 🇮🇷
- GEOIP,ir,سایتای ایرانی 🇮🇷
- IP-CIDR,10.10.34.0/24,نوع انتخاب پروکسی 🔀
- RULE-SET,apps,سایتای ایرانی 🇮🇷
- MATCH,نوع انتخاب پروکسی 🔀
ntp:
  enable: true
  server: time.apple.com
  port: 123
  interval: 30
