name: Generate Clash Configs

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install pyyaml requests

      - name: Run Config Generator
        run: python scripts/generator.py
        env:
          GITHUB_REPOSITORY: ${{ github.repository }} # هنوز برای پیام‌های لاگ مفید است

      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: auto-generate providers"
          # فقط فایل‌های providers/*.txt برای کامیت شدن انتخاب می‌شوند
          file_pattern: "providers/*.txt"
          commit_user_name: GitHub Actions Bot
          commit_user_email: actions@github.com
          commit_author: GitHub Actions Bot <actions@github.com>

